### ISSUE TITLE
Color YAML Keys just like HTML or XML tags

### ISSUE THREAD

**Issue by Leo383** [izhangzhihao/intellij-rainbow-brackets#2638]
**Please [support us](https://github.com/izhangzhihao/intellij-rainbow-brackets#support-us) before creating a feature request, thanks for your support 😁**

## Please check

- [ ] please do consider buy this plugin [here](https://www.jetbrains.com/shop/buy?item=P:N:PRAINBOWBRACKET:M) or donating us on [Open Collective](https://opencollective.com/intellij-rainbow-brackets) Or by AliPay/WeChatPay. 
- [x] This issue/feature request is not reported before.

## Your programming languages
YAML

## Expected Behavior
Indented keys cycle colors just like html/xml tags do.
It could look like this:
![yaml_future](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/44499435/3839de64-cb2f-4586-9e29-05d0c2e4cbc3)

## Current Behavior
Yaml files can be hard to read, when every key is the same color, even though it is a parent-child-sibling relationship just like html or xml.
Right now yaml files look like this:

![yaml_current](https://github.com/izhangzhihao/intellij-rainbow-brackets/assets/44499435/ecdad5f3-cbdb-400f-bf39-18bf1289eb88)

## Code examples

```yaml
---
# I am a comment
name: John D'vloper
job: Developer
skill: Elite
employed: True
foods:
  - Apple
  - Orange
  - Strawberry
  - Mango
languages:
  perl: Elite
  python: Elite
  pascal: Lame
education: |
  4 GCSEs
  3 A-Levels
  BSc in the Internet of Things
```
